# Generated by Django 4.2.1 on 2023-05-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image_url',
            field=models.URLField(default='https://media.istockphoto.com/id/1193057179/vector/photo-coming-soon-image-icon-vector-illustration-isolated-on-white-background-no-website.jpg?s=612x612&w=0&k=20&c=ewySSAlHhs8A97rqdS2sFrvExzs24k70n0uXeNC7peM='),
        ),
    ]
