# Generated by Django 4.2.1 on 2023-05-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image_url',
            field=models.URLField(default='https://media.istockphoto.com/id/1193057179/vector/photo-coming-soon-image-icon-vector-illustration-isolated-on-white-background-no-website.jpg?s=612x612&w=0&k=20&c=ewySSAlHhs8A97rqdS2sFrvExzs24k70n0uXeNC7peM=', max_length=2048),
        ),
    ]
